name: Deploy on PR Merge

on:
  pull_request:
    types:
      - closed  # Trigger only when PR is closed

jobs:
  check-comment-and-deploy:
    if: github.event.pull_request.merged == true  # Run only if the PR was merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Fetch PR comments
        id: fetch-comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: pr_number,
            });

            // Check if "deploy please" exists and if the author is "heloint"
            const triggerComment = comments.some(comment =>
              comment.body.toLowerCase().includes("deploy please") &&
              comment.user.login === "heloint"
            );

            console.log(`Trigger comment found: ${triggerComment}`);
            return triggerComment;

      - name: Deploy the application
        if: steps.fetch-comments.outputs.result == 'true'
        run: |
          echo "🚀 Deploying application..."
          # Place your actual deploy script here
